In [10]:
import json


import pandas as pd


#transactions_final

with open('transactions_final.json') as f:
    transactions = json.load(f)

list_trans_id = []

dict_transactions = {}

for key, transaction in transactions['transactions'].items():
    list_trans_id.append(key)
    for k, v in transaction.items():
        if not dict_transactions.get(k):
            dict_transactions[k] = []
            dict_transactions[k].append(v)
        else:
            dict_transactions[k].append(v)

dict_transactions['transaction_id'] = list_trans_id

In [11]:
df_new_pattern = pd.DataFrame(dict_transactions) # data frame для нового паттерна
df_new_pattern.head(4)

,date,card,account,account_valid_to,client,last_name,first_name,patronymic,date_of_birth,passport,passport_valid_to,phone,oper_type,amount,oper_result,terminal,terminal_type,city,address,transaction_id
0,2020-05-04T00:00:04,50785425162189603667,7456771640,2026-03-06,6-33721,Кадимов,Корнелиус,Ковалько,1993-09-17,2300733597,2027-12-11,+74304126656,Оплата,6734.10,Успешно,POS43792,POS,Нижний Новгород,"Нижний Новгород, ул. Короленковская, д. 5",3649235840
1,2020-05-04T00:01:19,57642678631657633216,7456771641,2025-08-15,6-33721,Кадимов,Корнелиус,Ковалько,1993-09-17,2300733597,2021-10-19,+74304126656,Снятие,69108.86,Отказ,POS43792,POS,Заречный,"Заречный, ул. Селянская, д. 57",3649235841
2,2020-05-04T00:02:51,50606101490380719590,7456771642,2034-09-08,2-10067,Котков,Валерьян,Байбаков,1946-09-08,3153290165,2006-07-07,+74832003245,Снятие,52699.45,Успешно,POS43792,POS,Донецк,"Донецк, ул. Возрождения, д. 23",3649235842
3,2020-05-04T00:04:16,40801177229019601602,7456771643,2033-12-14,7-17459,Сафьянов,Кондрат,Романцов,1965-11-27,3307023178,2031-11-17,+75914405368,Оплата,9705.71,Успешно,POS28311,POS,Красноуфимск,"Красноуфимск, ул. Старошишковская, д. 77",3649235843

In [12]:
df_new_pattern.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10233 entries, 0 to 10232
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               10233 non-null  object
 1   card               10233 non-null  object
 2   account            10233 non-null  object
 3   account_valid_to   10233 non-null  object
 4   client             10233 non-null  object
 5   last_name          10233 non-null  object
 6   first_name         10233 non-null  object
 7   patronymic         10233 non-null  object
 8   date_of_birth      10233 non-null  object
 9   passport           10233 non-null  object
 10  passport_valid_to  10233 non-null  object
 11  phone              10233 non-null  object
 12  oper_type          10233 non-null  object
 13  amount             10233 non-null  float64
 14  oper_result        10233 non-null  object
 15  terminal           10233 non-null  object
 16  terminal_type      10233 non-null  object
 17  city               10233 non-null  object
 18  address            10233 non-null  object
 19  transaction_id     10233 non-null  object
dtypes: float64(1), object(19)
memory usage: 1.6+ MB

In [13]:
# Удаляем ненужные столбцы
df_new_pattern.pop('account_valid_to')
df_new_pattern.pop('date_of_birth')
df_new_pattern.pop('city')
df_new_pattern.pop('oper_type')
df_new_pattern.pop('amount')
df_new_pattern.pop('oper_result')
df_new_pattern.pop('terminal')
df_new_pattern.pop('terminal_type')

0        POS
1        POS
2        POS
3        POS
4        POS
        ...
10228    POS
10229    POS
10230    POS
10231    POS
10232    POS
Name: terminal_type, Length: 10233, dtype: object

In [14]:
df_new_pattern.head()

,date,card,account,client,last_name,first_name,patronymic,passport,passport_valid_to,phone,address,transaction_id
0,2020-05-04T00:00:04,50785425162189603667,7456771640,6-33721,Кадимов,Корнелиус,Ковалько,2300733597,2027-12-11,+74304126656,"Нижний Новгород, ул. Короленковская, д. 5",3649235840
1,2020-05-04T00:01:19,57642678631657633216,7456771641,6-33721,Кадимов,Корнелиус,Ковалько,2300733597,2021-10-19,+74304126656,"Заречный, ул. Селянская, д. 57",3649235841
2,2020-05-04T00:02:51,50606101490380719590,7456771642,2-10067,Котков,Валерьян,Байбаков,3153290165,2006-07-07,+74832003245,"Донецк, ул. Возрождения, д. 23",3649235842
3,2020-05-04T00:04:16,40801177229019601602,7456771643,7-17459,Сафьянов,Кондрат,Романцов,3307023178,2031-11-17,+75914405368,"Красноуфимск, ул. Старошишковская, д. 77",3649235843
4,2020-05-04T00:05:56,57447203234952512132,7456771644,2-68359,Карельский,Алишер,Шавкунин,6750185314,2030-01-09,+74862414292,"Черкесск, ул. Гинтовта, д. 56",3649235844

In [15]:
# Собираем все паспорта
passports = []
for i in transactions["transactions"].keys():
    fio = transactions["transactions"][i]['passport']
    if fio not in passports:
        passports.append(fio)

In [16]:
# Собираем все транзакции для каждого пасспорта
trans_np = {}
for passport in passports:
    tran = df_new_pattern.loc[df_new_pattern['passport'] == passport]
    if not(trans_np.get(passport)):
        trans_np[passport] = [tran]
    else:
        trans_np[passport].append(tran)

In [17]:
# Находим кол-во транзакций и их время

ans = [0 for i in range(22)]
date_passport = {}
date_passport_ids = {}
for passort in trans_np.keys():

    a = trans_np[passort][0]
    a = pd.DataFrame(a)
    date_passport[passort] = a['date'].tolist()
    date_passport_ids[passort] = a['transaction_id'].tolist()
    count_trans = len(date_passport[passort])

    ans[count_trans] += 1

for i in range(len(ans)):
    print(i,':',ans[i])
# Кол-во транзакций от каждого пасспорта, Больше 20 транзакций никто не совершал

0 : 0
1 : 440
2 : 435
3 : 457
4 : 0
5 : 0
6 : 67
7 : 61
8 : 78
9 : 66
10 : 118
11 : 24
12 : 22
13 : 25
14 : 44
15 : 30
16 : 26
17 : 23
18 : 26
19 : 29
20 : 29
21 : 0

In [18]:

# Из таблицы выше можно сделать вывод о том, что обычные люди совершают от 1 до 3 транзакций,
# 4 и 5 транзакций никто не соверашл,
# а вот мошенники совершают от 6 до 20
# но нужно вычислить время, за которое были совершены эти транзакции
import datetime, time
def f(s): # переводим дату в секунды
    t = datetime.datetime(int(s[0:4]), int(s[5:7]), int(s[8:10]),int(s[11:13]),int(s[14:16]),int(s[17:]))
    return time.mktime(t.timetuple())

count_minutes = 8 # задаём кол-во минут, за которые были произведены транзакции оп новому паттерну
total_fraud_trans = 0
fraud_trans_ids = []

for i in date_passport.keys():
    date_fio_tran = date_passport[i]
    if len(date_fio_tran) >= 6:
        if ((f(date_passport[i][-1]) - f(date_passport[i][0]))) <= count_minutes * 60:
            total_fraud_trans += len(date_fio_tran)
            fraud_trans_ids += date_passport_ids[i]

        else: # Ищем максимальное кол-во транзакций, которые были произведены за count_minutes,
              # Если все транзакции этого фио не "поместились" в указанное кол-во минут

            max_trans = 0
            indexes = []
            seconds = list(map(f,date_passport[i]))

            for ind1 in range(len(date_passport[i])):
                for ind2 in range(ind1, len(date_passport[i])):
                    if ind1 != ind2 and ((f(date_passport[i][ind2]) - f(date_passport[i][ind1]))) <= count_minutes * 60:
                        if ind2 - ind1 + 1 > max_trans:
                            max_trans =  ind2 - ind1 + 1
                            indexes = [ind1,ind2]
            if len(indexes) > 0 and max_trans > 0:

                total_fraud_trans += len(date_fio_tran[indexes[0]:indexes[1]+1])
                fraud_trans_ids += date_passport_ids[i][indexes[0]:indexes[1]+1]



#ids_file = open('new_pattern_ids.txt','w')
#for id_oper in fraud_trans_ids:
#    ids_file.write(id_oper)
#    ids_file.write(', ')

#print(len(fraud_trans_ids) == len(set(fraud_trans_ids)))
#print(fraud_trans_ids)
print(count_minutes,'минут ==' ,total_fraud_trans, 'транзакций')

# 7552 транзакций, если очень большое кол-во минут и >= 6 транзакций
# 7552 транзакций, если 30 минут и >= 6 транзакций
# 28 минут == 7552 транзакций
# 27 минут == 7543 транзакций, то есть после если взять 27 минут и меньше, то кол-во fraud транзакций будет уменьшаться
# 26 минут == 7531 транзакций
# .....
# 8 минут == 4389 транзакций
# 7 минут == 3954 транзакций, то есть если брать целое кол-во минут, 7 минут и меньшу будут давать меньше 4 тысяч транзакций,
# а в условии сказано, что их должно быть больше 4 тысяч
# Вывод: если за 8 или больше минут было совершено 6 или больше транзакций, то такие транзакции попадают под новый паттерн и являются мошенническими
print(len(fraud_trans_ids))

8 минут == 4389 транзакций
4389